export const CREDIT_RULES = {
  EXPLORE_DAILY_COST: 1,
  EXPLORE_FORCE_REFRESH_COST: 10,
  SIGNUP_BONUS: 10,
  DAILY_ACTIVE_BONUS_VERIFIED: 3,
  DAILY_ACTIVE_BONUS_UNVERIFIED: 1,
  CONVERSATION_COST: 1,
  THIS_OR_THAT_APPROVAL_BONUS: 5,
  REFERRAL_VERIFICATION_BONUS: 10,
  REWARDED_AD_CREDIT: 1,
  REWARDED_AD_MAX_PER_HOUR: 3,
  REWARDED_AD_WINDOW_MS: 60 * 60 * 1000,
};
